### ISSUE TITLE
enabled flag is not respected

### ISSUE THREAD

**Issue by brennfoster** [thomasmichaelwallace/serverless-better-credentials#37]
**Describe the bug**
Setting the enabled flag to false does not prevent betterCredentials from running.

**To Reproduce**
Set enabled flag to false and run serverless

**Expected behavior**
It should prevent betterCredentials from running.

**Desktop (please complete the following information):**
 - Version 2.0.0
 - Serverless Version 3.38.0

Based on this piece of the README:
```
custom:
  betterCredentials:
    # Use this flag to turn off the plugin entirely, which you may want for certain stages.
    # Defaults to true.
    enabled: true
```
    
...  I'd expect that setting enabled to false would prevent betterCredentials from trying to obtain credentials.
